- type: entity
  id: VXSSpawnPointJobBase
  parent: SpawnPointJobBase
  abstract: true
  suffix: Job Spawn
  components:
  - type: Sprite
    sprite: VXS/Markers/jobs.rsi

- type: entity
  id: VXSSpawnPointSyndAnarchykeeperOfficer
  parent: VXSSpawnPointJobBase
  suffix: Synd
  name: Officer
  components:
  - type: SpawnPoint
    job_id: SyndAnarchykeeperOfficer
  - type: Sprite
    layers:
      - state: green
      - state: OfficerAnarchy

- type: entity
  id: VXSSpawnPointSyndAnarchykeeperCargoTechnician
  parent: VXSSpawnPointJobBase
  suffix: Synd
  name: Cargo Technician
  components:
  - type: SpawnPoint
    job_id: SyndAnarchykeeperCargoTechnician
  - type: Sprite
    layers:
      - state: green
      - state: CargoAnarchy

- type: entity
  id: VXSSpawnPointSyndAnarchykeeperEngineer
  parent: VXSSpawnPointJobBase
  suffix: Synd
  name: Engineer
  components:
  - type: SpawnPoint
    job_id: SyndAnarchykeeperEngineer
  - type: Sprite
    layers:
      - state: green
      - state: EngiAnarchy

- type: entity
  id: VXSSpawnPointSyndAnarchykeeperMedic
  parent: VXSSpawnPointJobBase
  suffix: Synd
  name: Medic
  components:
  - type: SpawnPoint
    job_id: SyndAnarchykeeperMedic
  - type: Sprite
    layers:
      - state: green
      - state: MedicAnarchy

- type: entity
  id: VXSSpawnPointSyndAnarchykeeper
  parent: VXSSpawnPointJobBase
  suffix: Synd
  name: Anarchykeeper
  components:
  - type: SpawnPoint
    job_id: SyndAnarchykeeper
  - type: Sprite
    layers:
      - state: green
      - state: Anarchy

- type: entity
  id: VXSSpawnPointSolfedPeacekeeper
  parent: VXSSpawnPointJobBase
  suffix: Solfed
  name: Peacekeeper
  components:
  - type: SpawnPoint
    job_id: SolfedPeacekeeper
  - type: Sprite
    layers:
      - state: green
      - state: Solfed

- type: entity
  id: VXSSpawnPointSolfedPeacekeeperOfficer
  parent: VXSSpawnPointJobBase
  suffix: Solfed
  name: Officer
  components:
  - type: SpawnPoint
    job_id: SolfedPeacekeeperOfficer
  - type: Sprite
    layers:
      - state: green
      - state: OfficerSolfed

- type: entity
  id: VXSSpawnPointSolfedPeacekeeperCargoTechnician
  parent: VXSSpawnPointJobBase
  suffix: Solfed
  name: Cargo Technician
  components:
  - type: SpawnPoint
    job_id: SolfedPeacekeeperCargoTechnician
  - type: Sprite
    layers:
      - state: green
      - state: CargoSolfed


- type: entity
  id: VXSSpawnPointSolfedPeacekeeperEngineer
  parent: VXSSpawnPointJobBase
  suffix: Solfed
  name: Engineer
  components:
  - type: SpawnPoint
    job_id: SolfedPeacekeeperEngineer
  - type: Sprite
    layers:
      - state: green
      - state: EngiSolfed

- type: entity
  id: VXSSpawnPointSolfedPeacekeeperMedic
  parent: VXSSpawnPointJobBase
  suffix: Solfed
  name: Medic
  components:
  - type: SpawnPoint
    job_id: SolfedPeacekeeperMedic
  - type: Sprite
    layers:
      - state: green
      - state: MedicSolfed

