- type: department
  id: SolarFederation
  name: department-solfed
  description: department-solfed-description
  color: "#318CE7"
  roles:
  - SolfedPeacekeeper
  - SolfedPeacekeeperMedic
  - SolfedPeacekeeperEngineer
  - SolfedPeacekeeperCargoTechnician
  - SolfedPeacekeeperOfficer

- type: department
  id: AnarchyFederation
  name: department-anarchy
  description: department-anarchy-description
  color: "#681c23"
  roles:
  - SyndAnarchykeeper
  - SyndAnarchykeeperMedic
  - SyndAnarchykeeperEngineer
  - SyndAnarchykeeperCargoTechnician
  - SyndAnarchykeeperOfficer
